version: "3.9"

networks:
  local-network:
    driver: bridge

volumes:
  poing-storage:
    external: false

services:
  # openssl: 
  #   build:
  #     context: ./openssl
  #     args:
  #       - DOMAIN=localhost.com
  #   volumes:
  #     - poing-storage:/etc/letsencrypt/

  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --agree-tos --no-eff-email --email poin.botg@gmail.com -d poing.tk
  #   volumes:
  #     - poing-storage/data/certbot/letsencrypt:/etc/letsencrypt
  #     - poing-storage/data/certbot/letsencrypts:/etc/letsencrypts
  #     - poing-storage/data/certbot/lib:/var/lib/letsencrypt

  nginx:
    # depends_on:
    #   - openssl
    build:
      context: ./nginx
      args:
        - NGINX_VERSION=1.23.1
    image: poingbot/image:nginx_1.0.0
    environment:
      - NGINX_VERSION=
    ports:
      - 80:80
      - 443:443
    volumes:
      - poing-storage:/etc/letsencrypt
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local-network
    links:
      - poing-api
      - poing-web

  local-redis:
    image: redis:alpine
    networks:
      - local-network
    volumes:
      - poing-storage:/data

  poing-api:
    depends_on:
      - local-redis
    build: ../poing-api
    image: poingbot/image:api_1.0.0
    networks:
      - local-network
    links:
      - local-redis

  poing-web:
    build: ../poing-web
    image: poingbot/image:web_1.0.0
    networks:
      - local-network
